### PR TITLE
Fix firefox bug by detecting invalid xml

### LINKED ISSUE #111: 204 (no content) responses return an XMLDocument in Firefox
When the server returns a 204, firefox sets `responseXML` to an XML document - a truthy object.

This is apparently a [long-standing Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=521301).

Since `xhr` is abstracting away `response`/`responseText`/`responseXML`, this means that `xhr` returns something other than null/undefined/empty string in Firefox when the server returns a 204.

https://github.com/Raynos/xhr/blob/master/index.js#L74

Would you be open to a pull request to fix this?  How would you prefer that this was fixed?  A check for a 204 status code that always returns null/undefined?  Or maybe return `responseText` as long as it's a string, so that an empty string is returned?

I've opened a pull request with a failing test: #112

### PR DESCRIPTION
**Pull request by TehShrike**
See #111, and discussion on  #112

This pull request depends on commits in #115

Fixes #111

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -69,7 +69,8 @@ function _createXHR(options) {
         if (xhr.response) {
             body = xhr.response
         } else if (xhr.responseType === "text" || !xhr.responseType) {
-            body = xhr.responseText || xhr.responseXML
+            var xml = (xhr.status === 204 && xhr.responseXML && xhr.responseXML.documentElement.nodeName === "parsererror") ? null : xhr.responseXML
```
Comment (naugtur) [inline index.js]: The more I look at it, the more I like the idea. It really does just eliminate the firefox bug and change no existing logic.

Comment (TehShrike) [inline index.js]: Yeah, it looks a bit uglier than the more general option, but it should be backwards compatible and releasable as a patch version.
