### PR TITLE
Don't use withCredentials on sync requests

### LINKED ISSUE #65: crash in Firefox when sync == true
when `sync == true`  `xhr` will crash with the following error:
```
InvalidAccessError: A parameter or an operation is not supported by the underlying object
```
On the line
```
xhr.withCredentials = !!options.withCredentials
```
On [the related MDN page](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) it is said that

    Note: Starting with Gecko 11.0 (Firefox 11.0 / Thunderbird 11.0 / SeaMonkey 2.8), Gecko no
    longer lets you use the withCredentials attribute when performing synchronous requests.
    Attempting to do so throws an NS_ERROR_DOM_INVALID_ACCESS_ERR exception.

### PR DESCRIPTION
**Pull request by brunal**
Avoid a crash on Firefox.
Fix #65

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -128,8 +128,9 @@ function createXHR(options, callback) {
     xhr.ontimeout = errorFunc
     xhr.open(method, uri, !sync)
     //has to be after open
-    xhr.withCredentials = !!options.withCredentials
-    
+    if(!sync)
```
Comment (naugtur) [inline index.js]: curly braces are missing, but I'll take care of it
